// components/ui/Input.tsx
import React from 'react'

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
	label?: string
	error?: string
	helperText?: string
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
	({ label, error, helperText, className = '', ...props }, ref) => {
		return (
			<div className="flex flex-col gap-1.5">
				{label && (
					<label className="block text-sm font-medium text-gray-700">
						{label}
						{props.required && <span className="text-red-600 ml-1">*</span>}
					</label>
				)}
				<input
					ref={ref}
					className={`px-4 py-2 border rounded-lg text-base focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed ${
						error ? 'border-red-600 focus:ring-red-600' : 'border-gray-300'
					} ${className}`}
					{...props}
				/>
				{error && <p className="text-sm text-red-600">{error}</p>}
				{helperText && <p className="text-sm text-gray-500">{helperText}</p>}
			</div>
		)
	}
)

Input.displayName = 'Input'

// src/components/ui/Input.vue
<template>
  <div class="flex flex-col gap-1">
    <label v-if="label" class="text-sm font-medium text-gray-700 dark:text-gray-300">
      {{ label }}
    </label>
    <div class="relative">
      <input
        v-bind="$attrs"
        :value="modelValue"
        @input="$emit('update:modelValue', $event.target.value)"
        class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm dark:bg-gray-800 dark:border-gray-700 dark:text-white px-3 py-2 border"
        :class="{ 'border-red-500 focus:border-red-500 focus:ring-red-500': error }"
      />
    </div>
    <p v-if="error" class="text-xs text-red-500">{{ error }}</p>
  </div>
</template>

<script setup>
defineProps({
  modelValue: [String, Number],
  label: String,
  error: String
})
defineEmits(['update:modelValue'])
</script>
